#!/usr/bin/env bash
# Transfer a file from to the home directory of a remote machine using the scp command.
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# The args will be passed to scp like so:
#       scp -o strictHostKeyChecking=no -i <PATH_TO_SSH_KEY> <PATH_TO_FILE> <USERNAME>@<IP>:~>

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~"
fi
