#!/usr/bin/env bash

apt-get update
apt-get install -y nginx

html_dir="/etc/nginx/html"
index_file="$html_dir/index.html"
nginx_default_config="/etc/nginx/sites-available/default"

# Check if the directory exists, create it if not
if [ ! -d "$html_dir" ]; then
    mkdir -p "$html_dir"
fi

# Check if the index file exists, create it if not
if [ ! -e "$index_file" ]; then
    touch "$index_file"
fi

# Check if the index file is writable, write to it if so
if [ -w "$index_file" ]; then
    echo "Hello World!" > "$index_file"
else
    >&2 echo "Error: Unable to write to $index_file. Check permissions."
fi

# Check if the Nginx default config file exists, write to it if so
if [ -e "$nginx_default_config" ]; then
    printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > "$nginx_default_config"
else
    >&2 echo "Error: Nginx default config file not found at $nginx_default_config."
fi

# Restart Nginx
service nginx restart
