#!/usr/bin/env bash
# Install nginx, set up root page, and set up up a redirect from /redirect_me

apt-get update
apt-get install -y nginx

html_dir="/var/www/html"
index_file="$html_dir/index.html"
nginx_default_config="/etc/nginx/sites-available/default"

# Check if the directory exists, create it if not
if [ ! -d "$html_dir" ]; then
    mkdir -p "$html_dir"
fi

# Check if the index file exists, create it if not
if [ ! -e "$index_file" ]; then
    touch "$index_file"
fi

# Check if the index file is writable, write to it if so
if [ -w "$index_file" ]; then
    echo "Hello World!" > "$index_file"
else
    >&2 echo "Error: Unable to write to $index_file. Check permissions."
fi

# Create file to be served in case of an error 404
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Check if the Nginx default config file exists, write to it if so
if [ -e "$nginx_default_config" ]; then
    printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    error_page 404 /404.html;
    index  index.html index.htm index.nginx-debian.html;
    add_header X-Served-By $HOSTNAME;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > "$nginx_default_config"
else
    >&2 echo "Error: Nginx default config file not found at $nginx_default_config."
fi

# Enable the server block
if [ ! -e /etc/nginx/sites-enabled/default ]; then
    ln -s "$nginx_default_config" /etc/nginx/sites-enabled/default
fi

# Restart Nginx
service nginx restart
