#!/usr/bin/env bash
# Install HAproxy and configure it to route traffic to two servers using
# the roundrobin algorithm

# Specify the software version for reproducibility.
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

# Configure HAProxy
echo "\
defaults
    mode http
    timeout client 10s
    timeout connect 5s
    timeout server 10s
    timeout http-request 10s

frontend peterndungu.tech
    bind :80
    default_backend webservers

backend webservers
    balance roundrobin
    server 342444-web-01 100.26.142.27:80  check
    server 342444-web-02 107.22.146.148:80 check" > /etc/haproxy/haproxy.cfg

sudo service haproxy restart
