#!/usr/bin/env bash
# Configure Nginx to listen to port 80 and then ... kill it!
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill -o nginx
