#!/usr/bin/env bash
# Extract the username, user id and home directory from each line of
# the /etc/passwd file.
# The format for each line is: username:password:UID:GID:GECOS:home_directory:shell

while read -r line; do
    echo "$line" | cut -d ":" -f 1,3,6
done < /etc/passwd
