#!/usr/bin/env bash
# Use various file test operators to inspect a file

fname="school"

if [ -e "$fname" ]; then
    echo "$fname file exists"

    file_size=$(stat -c %s "$fname")
    if [ "$file_size" -eq 0 ]; then
        echo "$fname file is empty"
    else
        echo "$fname file is not empty"
    fi
    if [ -f $fname ]; then
        echo "$fname is a regular file"
    fi

else
    echo "$fname file does not exist"
fi
